/* Movable Type language lexicon for es localization. */

Lexicon['Add sub category'] = 'Añadir sub categoría';
Lexicon['remove'] = 'borrar';
Lexicon['Make primary'] = 'Hacer primario';
Lexicon['Are you sure you want to remove the [_1] selected [_2] from this group?'] = '¿Está seguro de querer borrar el [_1] seleccionado [_2] de este grupo?';
Lexicon['Last auto-save at [_1]:[_2]:[_3]'] = 'Último guardado automático a las [_1]:[_2]:[_3]';
Lexicon['Remove'] = 'Borrar';
Lexicon['Enter email address:'] = 'Teclee la dirección de correo-e:';
Lexicon['Are you certain you want to remove these [_1] roles? By doing so you will be taking away the permissions currently assigned to any users and groups associated with these roles.'] = '¿Está seguro de que desea borrar estos [_1] roles? Al hacerlo, eliminará los permisos actualmente asignados a cualquier usuario o grupo relacionados con estos roles.';
Lexicon['You have \<a href=\'[_3]\'\>[quant,_1,entry,entries] from [_2]\<\/a\>'] = 'Tiene \<a href=\'[_3]\'\>[quant,_1,entrada] de [_2]\<\/a\>';
Lexicon['Cancel'] = 'Cancelar';
Lexicon['No Preview Available'] = 'Sin vista previa disponible';
Lexicon['An error occurred while testing for the new tag name.'] = 'Ocurrió un error mientras se probaba el nuevo nombre de la etiqueta.';
Lexicon['[_1]Publish[_2] your site to see these changes take effect.'] = '[_1]Publique[_2] el sitio para que los cambios tomen efecto.';
Lexicon['Are you sure you want to remove this [_1]?'] = '¿Está seguro de querer borrar esto [_1]?';
Lexicon['View uploaded file'] = 'Mostrar fichero transferido';
Lexicon['Loading...'] = 'Cargando...';
Lexicon['to mark as spam'] = 'para marcar como spam';
Lexicon['Auto-saving...'] = 'Auto-guardando...';
Lexicon['You can only act upon a minimum of [_1] [_2].'] = 'Solo puede actuar sobre un mínimo de [_1] [_2].';
Lexicon['Are you certain you want to remove this role? By doing so you will be taking away the permissions currently assigned to any users and groups associated with this role.'] = '¿Está seguro de que desea borrar este rol? Al hacerlo, eliminará los permisos actualmente asignados a cualquier usuario o grupo relacionados con este rol.';
Lexicon['Are you sure you want to [_3] the [_1] selected [_2]?'] = '¿Está seguro de que desea [_3] el/los [_1] seleccionado/s [_2]?';
Lexicon['delete'] = 'borrar';
Lexicon['You have [quant,_1,registration,registrations] from [_2]'] = 'Tiene un [quant,_1,registro,registros] en [_2]';
Lexicon['Are you sure you want to remove this [_1] from this group?'] = '¿Está seguro de querer borrar este [_1] de este grupo?';
Lexicon['You did not select any [_1] to [_2].'] = 'No seleccionó ninguna [_1] sobre la que [_2].';
Lexicon['to remove spam status'] = 'para desmarcar como spam';
Lexicon['Enter URL:'] = 'Teclee la URL:';
Lexicon['to remove'] = 'para borrar';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all blogs?'] = 'La etiqueta \'[_2]\' ya existe.  ¿Está seguro de querer combinar \'[_1]\' con \'[_2]\' en todos los blogs?';
Lexicon['None selected'] = 'Ninguna seleccionada';
Lexicon['You have \<a href=\'[_3]\'\>[quant,_1,comment,comments] from [_2]\<\/a\>'] = 'Tiene \<a href=\'[_3]\'\>[quant,_1,comentario,comentarios] de [_2]\<\/a\>';
Lexicon['Are you sure you want to remove the [_1] selected [_2]?'] = '¿Está seguro de querer borrar el [_1] seleccionado [_2]?';
Lexicon['You must select an action.'] = 'Debe seleccionar una acción.';
Lexicon['You did not select any [_1] [_2].'] = 'No seleccionó ninguna [_1] [_2].';
Lexicon['You did not select any [_1] to remove.'] = 'No ha seleccionado ningún [_1] a borrar.';
Lexicon['disable'] = 'deshabilitar';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\'?'] = 'La etiqueta \'[_2]\' ya existe. ¿Está seguro de que desea integrar \'[_1]\' y \'[_2]\'?';
Lexicon['enable'] = 'habilitar';
Lexicon['You can only act upon a maximum of [_1] [_2].'] = 'Solo puede actuar sobre un máximo de [_1] [_2].';
Lexicon['(None)'] = '(Ninguno)';
Lexicon['Close'] = 'Cerrar';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all weblogs?'] = 'La etiqueta \'[_2]\' ya existe. ¿Está seguro de que desea integrar \'[_1]\' y \'[_2]\' en todos los weblogs?';
Lexicon['Are you sure you want to [_2] this [_1]?'] = '¿Está seguro de que desea [_2] esta [_1]?';
