/* Movable Type language lexicon for nl localization. */

Lexicon['Add sub category'] = 'Subcategorie toevoegen';
Lexicon['remove'] = 'verwijderen';
Lexicon['Make primary'] = 'Maak dit een hoofdcategorie';
Lexicon['Are you sure you want to remove the [_1] selected [_2] from this group?'] = 'Bent u zeker dat u de [_1] geselecteerde [_2] wenst te verwijderen uit deze groep?';
Lexicon['Last auto-save at [_1]:[_2]:[_3]'] = 'Laatste auto-opslag om [_1]:[_2]:[_3]';
Lexicon['Remove'] = 'Verwijder';
Lexicon['Enter email address:'] = 'Voer e-mail adres in:';
Lexicon['Are you certain you want to remove these [_1] roles? By doing so you will be taking away the permissions currently assigned to any users and groups associated with these roles.'] = 'Bent u zeker dat u deze [_1] rollen wenst te verwijderen?  Door dit te doen worden de permissies weggenomen van gebruikers en groepen die momenteel met deze rollen geassocieerd zijn.';
Lexicon['You have \<a href=\'[_3]\'\>[quant,_1,entry,entries] from [_2]\<\/a\>'] = 'U heeft \<a href=\'[_3]\'\>[quant,_1,bericht,berichten] van [_2]\<\/a\>';
Lexicon['Cancel'] = 'Annuleren';
Lexicon['No Preview Available'] = 'Geen voorbeeld beschikbaar';
Lexicon['An error occurred while testing for the new tag name.'] = 'Er deed zich een fout voor bij het testen op de nieuwe tagnaam.';
Lexicon['[_1]Publish[_2] your site to see these changes take effect.'] = '[_1]Publiceer[_2] uw site om deze wijzigingen zichtbaar te maken.';
Lexicon['[_1] &ndash; [_2] of [_3]'] = '[_1] &ndash; [_2] van [_3]';
Lexicon['Are you sure you want to remove this [_1]?'] = 'Bent u zeker dat u deze [_1] wenst te verwijderen?';
Lexicon['View uploaded file'] = 'Opgeladen bestand bekijken';
Lexicon['Loading...'] = 'Laden...';
Lexicon['to mark as spam'] = 'om als spam aan te merken';
Lexicon['Auto-saving...'] = 'Auto-opslaan...';
Lexicon['You can only act upon a minimum of [_1] [_2].'] = 'U kunt enkel een handeling uitvoeren om minimaal [_1] [_2].';
Lexicon['Are you certain you want to remove this role? By doing so you will be taking away the permissions currently assigned to any users and groups associated with this role.'] = 'Bent u zeker dat u deze rol wenst te verwijderen?  Door dit te doen worden de permissies weggenomen van gebruikers en groepen die momenteel met deze rol geassocieerd zijn.';
Lexicon['Are you sure you want to [_3] the [_1] selected [_2]?'] = 'Bent u zeker dat u deze [_1] geselecteerde [_2] wenst te [_3]?';
Lexicon['delete'] = 'verwijderen';
Lexicon['You have [quant,_1,registration,registrations] from [_2]'] = 'U heeft [quant,_1,registratie,registraties] op [_2]';
Lexicon['Are you sure you want to remove this [_1] from this group?'] = 'Bent u zeker dat u deze [_1] wenst te verwijderen uit deze groep?';
Lexicon['You did not select any [_1] to [_2].'] = 'U selecteerde geen [_1] om te [_2].';
Lexicon['to remove spam status'] = 'om spamstatus van te verwijderen';
Lexicon['Enter URL:'] = 'Voer URL in:';
Lexicon['to remove'] = 'te verwijderen';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all blogs?'] = 'De tag \'[_2]\' bestaat al.  Zeker dat u \'[_1]\' en \'[_2]\' wenst samen te voegen over alle blogs?';
Lexicon['None selected'] = 'Geen geselecteerd';
Lexicon['You have \<a href=\'[_3]\'\>[quant,_1,comment,comments] from [_2]\<\/a\>'] = 'U heeft \<a href=\'[_3]\'\>[quant,_1,reactie,reacties] van [_2]\<\/a\>';
Lexicon['Are you sure you want to remove the [_1] selected [_2]?'] = 'Bent u zeker dat u de [_1] geselecteerde [_2] wenst te verwijderen?';
Lexicon['You must select an action.'] = 'U moet een handeling selecteren';
Lexicon['You did not select any [_1] [_2].'] = 'U selecteerde geen [_1] [_2]';
Lexicon['You did not select any [_1] to remove.'] = 'U selecteerde geen [_] om te verwijderen.';
Lexicon['disable'] = 'desactiveren';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\'?'] = 'De tag \'[_2]\' bestaat al.  Bent u zeker dat u \'[_1]\' met \'[_2]\' wenst samen te voegen?';
Lexicon['enable'] = 'activeren';
Lexicon['You can only act upon a maximum of [_1] [_2].'] = 'U kunt enkel een handeling uitvoeren op maximum [_1] [_2].';
Lexicon['(None)'] = '(Geen)';
Lexicon['Close'] = 'Sluiten';
Lexicon['The tag \'[_2]\' already exists. Are you sure you want to merge \'[_1]\' with \'[_2]\' across all weblogs?'] = 'De tag \'[_2]\' bestaat al.  Bent u zeker dat u \'[_1]\' met \'[_2]\' wenst samen te voegen over alle weblogs?';
Lexicon['Are you sure you want to [_2] this [_1]?'] = 'Opgelet: [_1] echt [_2]?';
